# Generated by Django 5.1.4 on 2025-05-01 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('clave', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_periodo', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('grupo', models.CharField(max_length=5)),
                ('cupo_maximo', models.PositiveIntegerField(default=30)),
                ('dia', models.CharField(choices=[('LUN', 'Lunes'), ('MAR', 'Martes'), ('MIE', 'Miércoles'), ('JUE', 'Jueves'), ('VIE', 'Viernes'), ('SAB', 'Sábado'), ('DOM', 'Domingo')], max_length=3)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('edificio', models.CharField(max_length=50)),
                ('numero_salon', models.CharField(max_length=10)),
                ('tipo_salon', models.CharField(choices=[('AULA', 'Aula regular'), ('LAB', 'Laboratorio'), ('TALLER', 'Taller'), ('AUDITORIO', 'Auditorio')], default='AULA', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=150)),
                ('apellidoPaterno', models.CharField(max_length=150)),
                ('apellidoMaterno', models.CharField(max_length=150)),
                ('curp', models.CharField(max_length=45, unique=True)),
                ('promedio', models.FloatField(blank=True, null=True)),
                ('semestre_actual', models.PositiveSmallIntegerField(default=1)),
                ('urlFoto', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('carrera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumnos', to='SchoolAPI.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('clave', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'unique_together': {('nombre', 'clave')},
            },
        ),
        migrations.AddField(
            model_name='carrera',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carreras', to='SchoolAPI.departamento'),
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('calificacion', models.FloatField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='SchoolAPI.alumno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='SchoolAPI.curso')),
            ],
            options={
                'unique_together': {('alumno', 'curso')},
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=125)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('creditos', models.IntegerField()),
                ('carrera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materias', to='SchoolAPI.carrera')),
            ],
            options={
                'unique_together': {('nombre', 'codigo')},
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='SchoolAPI.materia'),
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula_profesional', models.CharField(max_length=15, unique=True)),
                ('nombres', models.CharField(max_length=150)),
                ('apellidoPaterno', models.CharField(max_length=150)),
                ('apellidoMaterno', models.CharField(max_length=150)),
                ('urlFoto', models.URLField(blank=True)),
                ('es_director', models.BooleanField(default=False)),
                ('salario', models.FloatField(blank=True, null=True)),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profesores', to='SchoolAPI.departamento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='profesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos', to='SchoolAPI.profesor'),
        ),
        migrations.AlterUniqueTogether(
            name='carrera',
            unique_together={('nombre', 'clave')},
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('presente', models.BooleanField(default=False)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='SchoolAPI.inscripcion')),
            ],
            options={
                'unique_together': {('inscripcion', 'fecha')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together={('edificio', 'numero_salon', 'dia', 'hora_inicio'), ('materia', 'grupo', 'nombre_periodo')},
        ),
    ]
